version: '3.1'

services:
  db:
    image: mysql:8.4.0
    restart: always
    ports:
    - "3506:3306"
    environment:
      MYSQL_ROOT_PASSWORD: <YOUR_PASSWORD>
  #     # MYSQL_USER:
  #     # MYSQL_PASSWORD:

  clickhouse:
    image: clickhouse/clickhouse-server
    restart: always
    ports:
      - 8123:8123 
      - 9000:9000
      - 9100:9100
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    # volumes:
    # - ./clickhouse/data:/var/lib/clickhouse/
    # - ./clickhouse/server:/var/log/clickhouse-server/